# This file configures the analyzer for the example app
# Uses the parent package's very_good_analysis configuration

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Allow print in example code for debugging and demonstration
    avoid_print: false
    
    # Allow implementation imports in example code
    implementation_imports: false
    
    # Allow BuildContext across async gaps in examples
    use_build_context_synchronously: false
    
    # Don't require const everywhere in examples
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
